// nord-react-tanstack-table/src/DataTable/DataTable.tsx
import { useEffect } from "react";
import { flexRender, Table as TanstackTable } from "@tanstack/react-table";

import "./DataTable.css";
import { ResizeHandle } from "./ResizeHandle.js";
import { SortButton } from "./SortButton.js";

const ariaSortMap = {
  default: "none",
  asc: "ascending",
  desc: "descending",
} as const;

function usePreventSelection(prevent: boolean) {
  useEffect(() => {
    const userSelect = prevent ? "none" : "";
    document.body.style.setProperty("user-select", userSelect);
    document.body.style.setProperty("-webkit-user-select", userSelect);
  }, [prevent]);
}

export function DataTable<TData>({ table }: { table: TanstackTable<TData> }) {
  const isResizing = table
    .getAllFlatColumns()
    .some((col) => col.getIsResizing());

  usePreventSelection(isResizing);

  return (
    <nord-table className={isResizing ? "is-resizing" : ""}>
      <table>
        <thead>
          {table.getHeaderGroups().map((headerGroup) => (
            <tr key={headerGroup.id}>
              {headerGroup.headers.map((header) => {
                if (header.isPlaceholder) {
                  return <th key={header.id}></th>;
                }

                return (
                  <th
                    key={header.id}
                    style={{
                      width: header.getSize(),
                      ...(header.column.columnDef?.meta as any)?.style,
                    }}
                    onClick={header.column.getToggleSortingHandler()}
                    aria-sort={
                      header.column.getCanSort()
                        ? ariaSortMap[header.column.getIsSorted() || "default"]
                        : undefined
                    }
                  >
                    {flexRender(
                      header.column.columnDef.header,
                      header.getContext()
                    )}
                    {header.column.getCanSort() && (
                      <SortButton header={header} />
                    )}
                    {header.column.getCanResize() && (
                      <ResizeHandle header={header} />
                    )}
                  </th>
                );
              })}
            </tr>
          ))}
        </thead>

        <tbody>
          {table.getRowModel().rows.map((row) => (
            <tr key={row.id}>
              {row.getVisibleCells().map((cell) => (
                <td
                  key={cell.id}
                  className={
                    (cell.column.columnDef?.meta as any)?.truncate
                      ? "n-table-ellipsis"
                      : ""
                  }
                  style={{
                    width: cell.column.getSize(),
                    ...(cell.column.columnDef?.meta as any)?.style,
                  }}
                >
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </nord-table>
  );
}

// nord-vue-tanstack-table/src/components/DataTable/DataTable.vue
<script setup lang="ts">
import { watchEffect, computed } from "vue";
import { FlexRender } from "@tanstack/vue-table";
import type { Table } from "@tanstack/vue-table";
import ResizeHandle from "./ResizeHandle.vue";
import SortButton from "./SortButton.vue";

const { table } = defineProps<{ table: Table<any> }>();

const ariaSortMap = {
  default: "none",
  asc: "ascending",
  desc: "descending",
} as const;

const isResizing = computed(() =>
  table.getAllFlatColumns().some((col) => col.getIsResizing())
);

watchEffect(() => {
  const userSelect = isResizing.value ? "none" : "";
  document.body.style.setProperty("user-select", userSelect);
  document.body.style.setProperty("-webkit-user-select", userSelect);
});
</script>

<template>
  <nord-table :class="{ 'is-resizing': isResizing }">
    <table>
      <thead>
        <tr
          v-for="headerGroup in table.getHeaderGroups()"
          :key="headerGroup.id"
        >
          <th
            v-for="header in headerGroup.headers"
            :key="header.id"
            :aria-sort="
              header.column.getCanSort()
                ? ariaSortMap[header.column.getIsSorted() || 'default']
                : undefined
            "
            :style="{
              width: `${header.getSize()}px`,
              ...(header.column.columnDef?.meta as any)?.style,
            }"
            @click="header.column.getToggleSortingHandler()?.($event)"
          >
            <template v-if="!header.isPlaceholder">
              <FlexRender
                :render="header.column.columnDef.header"
                :props="header.getContext()"
              />
              <SortButton v-if="header.column.getCanSort()" :header="header" />
              <ResizeHandle
                v-if="header.column.getCanResize()"
                :header="header"
              />
            </template>
          </th>
        </tr>
      </thead>

      <tbody>
        <tr v-for="row in table.getRowModel().rows" :key="row.id">
          <td
            v-for="cell in row.getVisibleCells()"
            :key="cell.id"
            :style="{
              width: `${cell.column.getSize()}px`,
              ...(cell.column.columnDef?.meta as any)?.style,
            }"
            :class="{
              'n-table-ellipsis': (cell.column.columnDef?.meta as any)?.truncate,
            }"
          >
            <FlexRender
              :render="cell.column.columnDef.cell"
              :props="cell.getContext()"
            />
          </td>
        </tr>
      </tbody>
    </table>
  </nord-table>
</template>

<style scoped>
table {
  table-layout: fixed;
}

nord-table.is-resizing * {
  cursor: col-resize !important;
}

nord-table th[aria-sort] {
  cursor: pointer;
}

nord-table th[aria-sort]:not([aria-sort="none"]) {
  color: var(--n-color-text);
}
</style>
