// nord-vue-ag-grid/src/components/DataTable/CustomHeader.vue
<script setup lang="ts">
import { ref } from "vue";
import { IHeaderParams } from "ag-grid-community";
import { useEventListener } from "../../utils/events.js";
import SortButton from "./SortButton.vue";

const { params } = defineProps<{ params: IHeaderParams }>();

const textAlign: "end" | undefined =
  params.column.getColDef().type === "rightAligned" ? "end" : undefined;

const sortOrderMap = {
  default: "asc",
  asc: "desc",
  desc: null,
} as const;

const sort = ref(params.column.getSort());
useEventListener(params.column, "sortChanged", () => {
  sort.value = params.column.getSort();
});

const updateSort = (event: MouseEvent) => {
  if (params.enableSorting) {
    const newSort = sortOrderMap[sort.value ?? "default"];
    params.setSort(newSort, event.shiftKey);
  }
};
</script>

<template>
  <div :style="{ textAlign }" @click="updateSort">
    {{ params.displayName }}
    <SortButton v-if="params.enableSorting" :sort="sort" />
  </div>
</template>

// nord-react-ag-grid/src/DataTable/CustomHeader.tsx
import { IHeaderParams } from "ag-grid-community";
import { SortButton } from "./SortButton.js";

const sortOrderMap = {
  default: "asc",
  asc: "desc",
  desc: null,
} as const;

export function CustomHeader({
  enableSorting,
  column,
  setSort,
  displayName,
}: IHeaderParams) {
  const textAlign =
    column.getColDef().type === "rightAligned" ? "end" : undefined;

  return (
    <div
      style={{ textAlign }}
      onClick={(event) => {
        if (enableSorting) {
          const order = sortOrderMap[column.getSort() || "default"];
          setSort(order, event.shiftKey);
        }
      }}
    >
      {displayName}
      {enableSorting && <SortButton sort={column.getSort()} />}
    </div>
  );
}
