// nord-vue-ag-grid/src/components/DataTable/DataTable.vue
<script setup lang="ts">
import "ag-grid-community/styles/ag-grid.css";
import "@nordhealth/ag-theme-nord";

import {
  GridOptions,
  GridReadyEvent,
  ModuleRegistry,
  AllCommunityModule,
  provideGlobalGridOptions,
} from "ag-grid-community";
import { AgGridVue } from "ag-grid-vue3";
import CustomHeader from "./CustomHeader.vue";

const { columns, defaultColumn, data, components } = defineProps<{
  columns: GridOptions["columnDefs"];
  defaultColumn: GridOptions["defaultColDef"];
  components?: GridOptions["components"];
  data: any;
}>();

ModuleRegistry.registerModules([AllCommunityModule]);

provideGlobalGridOptions({
  theme: "legacy",
});

const onGridReady = (params: GridReadyEvent) => {
  params.api.sizeColumnsToFit();
  params.api.setGridOption("domLayout", "autoHeight");
};
</script>

<template>
  <div class="ag-theme-nord" :style="{ width: '100%' }">
    <AgGridVue
      :columnDefs="columns"
      :defaultColDef="defaultColumn"
      :rowData="data"
      :components="{ agColumnHeader: CustomHeader, ...components }"
      @grid-ready="onGridReady"
      :suppressRowTransform="true"
    />
  </div>
</template>

// nord-react-ag-grid/src/DataTable/DataTable.tsx
import { AgGridReact } from "ag-grid-react";
import {
  ColDef,
  GridReadyEvent,
  ModuleRegistry,
  AllCommunityModule,
  provideGlobalGridOptions,
} from "ag-grid-community";
import "ag-grid-community/styles/ag-grid.css";
import "@nordhealth/ag-theme-nord";
import "./DataTable.css";

import { CustomHeader } from "./CustomHeader";

const components = {
  agColumnHeader: CustomHeader,
};

ModuleRegistry.registerModules([AllCommunityModule]);

provideGlobalGridOptions({
  theme: "legacy",
});

const onGridReady = (params: GridReadyEvent) => {
  params.api.sizeColumnsToFit();
  params.api.setGridOption("domLayout", "autoHeight");
};

export function DataTable<TData>({
  columns,
  data,
  defaultColumn,
}: {
  columns: ColDef<TData>[];
  data: TData[];
  defaultColumn: ColDef<TData>;
}) {
  return (
    <div className="ag-theme-nord" style={{ width: "100%" }}>
      <AgGridReact<TData>
        columnDefs={columns}
        rowData={data}
        defaultColDef={defaultColumn}
        onGridReady={onGridReady}
        components={components}
        suppressRowTransform={true}
      />
    </div>
  );
}
